persona:
    path:     /
    defaults: { _controller: "ChecnesRegistroBundle:Persona:index" }

persona_show:
    path:     /{id}/show
    defaults: { _controller: "ChecnesRegistroBundle:Persona:show" }

persona_new:
    path:     /new
    defaults: { _controller: "ChecnesRegistroBundle:Persona:new" }

persona_create:
    path:     /create
    defaults: { _controller: "ChecnesRegistroBundle:Persona:create" }
    methods:  POST

persona_edit:
    path:     /{id}/edit
    defaults: { _controller: "ChecnesRegistroBundle:Persona:edit" }

persona_update:
    path:     /{id}/update
    defaults: { _controller: "ChecnesRegistroBundle:Persona:update" }
    methods:  [POST, PUT]

persona_delete:
    path:     /{id}/delete
    defaults: { _controller: "ChecnesRegistroBundle:Persona:delete" }
    methods:  [POST, DELETE]
