oneup_uploader:
    resource: .
    type: uploader

crece_registro:
    resource: "@CreceRegistroBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
